#::::::= Task:4 :::::
# Question : 1
name1=input("Enter Your Name  ")
print(name1)
name2=input("Enter Your Name  ")
print(name2)
name3=input("Enter Your Name  ")
print(name3)
name4=input("Enter Your Name  ")
print(name4)
name5=input("Enter Your Name  ")
print(name5)
name6=input("Enter Your Name  ")
print(name6)
name7=input("Enter Your Name  ")
print(name7)
name8=input("Enter Your Name  ")
print(name8)
name9=input("Enter Your Name  ")
print(name9)
name10=input("Enter Your Name  ")
print(name10)

height1=input("Enter Your HEIGHT ")
print(height1)
height2=input("Enter Your HEIGHT  ")
print(height2)
height3=input("Enter Your HEIGHT ")
print(height3)
height4=input("Enter Your HEIGHT ")
print(height4)
height5=input("Enter Your HEIGHT  ")
print(height5)
height6=input("Enter Your HEIGHT ")
print(height6)
height7=input("Enter Your HEIGHT ")
print(height7)
height8=input("Enter Your HEIGHT ")
print(height8)
height9=input("Enter Your HEIGHT ")
print(height9)
height10=input("Enter Your HEIGHT ")
print(height10)

num1=int(input("Enter Your Mobile Number "))
print(num1)
num2=int(input("Enter Your Mobile Number  "))
print(num2)
num3=int(input("Enter Your Mobile Number  "))
print(num3)
num4=int(input("Enter Your Mobile Number"))
print(num4)
num5=int(input("Enter Your Mobile Number  "))
print(num5)
num6=int(input("Enter Your Mobile Number  "))
print(num6)
num7=int(input("Enter Your Mobile Number "))
print(num7)
num8=int(input("Enter Your Mobile Number  "))
print(num8)
num9=int(input("Enter Your Mobile Number "))
print(num9)
num10=int(input("Enter Your Mobile Number "))
print(num10)

data={"NAMES":[name1,name2,name3,name4,name5,name6,name7,name8], "HEIGHT " : [height1,height2,height3,height4,height5,height6,height7,height8,height9,height10] ,"Mobile Numbers": [num1,num2,num3,num4,num5,num6,num7,num8,num9,num10]}
print(data)

#Question:2 Design an online admission form for Skillvention
name=input("Enter Your Name = " )
print(name)
email=input("Enter Your Email adress = ")
print(email)
number=int(input("Enter your mobile number ,it can only be digits  "))
print(number)
guardian=input("Enter Your Guardian Name ")
print(guardian)
gurdian_num=input("Enter guardian Contact number,it should be in digits ")
print(gurdian_num)
# Task 3:Create login and regestration form for Your Website
print("Please login here or Sign up if You don't have account")
#create login form
username=input("Please Enter Your username ")
print(username)
password=input("Enter Your Password ")
print(password)
print("The Verification Code has sent to Your Mobile Number Please enter The 6 digits code ")
code=input()
print(code)
